### ISSUE TITLE
About the boundary

### ISSUE THREAD

**Issue by smallrainbow** [PrincetonUniversity/tristan-mp-v2#1]
@haykh 
Dear developer，

Is it possible to add an injector and reflection boundary as in previous work by Tristan?

E.g.,
https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.114.085003
Or
https://www.researchgate.net/publication/1785397_Simulations_of_relativistic_collisionless_shocks_shock_structure_and_particle_acceleration

I find that the recent version only supports periodic, outflow and radiation boundaries.
Thank you very much!

Best regards,
Zhongwei

**Comment by haykh** [comment]
Dear Zhongwei,

We are actually preparing a major update before 2021 with lots of new features including reflecting wall (e.g. shock setup), new output capabilities etc. Stay tuned.

**Comment by haykh** [comment]
@smallrainbow, we updated the code as promised. Please see the [f.a.q.](https://ntoles.github.io/tristan-wiki/tristanv2-faq.html#how-to-set-up-reflecting-boundary-conditions) for your use case.

**Comment by smallrainbow** [comment]
Dear Hayk,
Thank you very much for your efforts.
Best wishes & happy new year!
Zhongwei

Hayk <notifications@github.com> 于2020年12月23日周三 下午1:32写道：
