### ISSUE TITLE
Having trouble compiling on an AMD machine

### ISSUE THREAD

**Issue by rgill3141** [PrincetonUniversity/tristan-mp-v2#10]
Hi Hayk,

I'm trying to compile the latest version of the code on an AMD machine, but it is failing when trying to compile the exchange_particles.F90 file. The compilation command that I'm using is the follows (using the example posted on the code website):

`Compilation command:     h5pfc -DHDF5 -DMPI08 -DtwoD -DNGHOST=3 -Ofast -O3 -DSoA -ffree-line-length-512 -DSTR_MAX=280 -DTINYXYZ=1e-6 -DTINYREAL=1e-3 -DTINYFLD=1e-8 -DTINYWEI=1e-6 -DM_PI=3.141592653589793 -DVEC_LEN=16 -Ddefault_h5_real=H5T_NATIVE_REAL`

I also tried using `-mpi` but I get a different error but for the same file.

To give you an idea of the kind of system I have, the `lscpu` command gives:

`Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             4
NUMA node(s):          8
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 2
Model name:            AMD Opteron(tm) Processor 6376
Stepping:              0
CPU MHz:               1400.000
CPU max MHz:           2300.0000
CPU min MHz:           1400.0000
BogoMIPS:              4600.26
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             64K
L2 cache:              2048K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15
NUMA node2 CPU(s):     16-23
NUMA node3 CPU(s):     24-31
NUMA node4 CPU(s):     32-39
NUMA node5 CPU(s):     40-47
NUMA node6 CPU(s):     48-55
NUMA node7 CPU(s):     56-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd rsb_ctxsw ibpb vmmcall bmi1 retpoline_amd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold`

I'm using the following software to the compile the code, installed using conda: `GCC-13.2.0`, `OpenMPI-4.1.6`, and the latest version of HDF5 (parallel) built using the compilers mentioned before.

The **error** that I'm getting is the following:

src/communications/exchange_particles.F90:17:23:

   17 |     type(MPI_DATATYPE), dimension(0:2) :: oldtypes
      |                       1
Error: Derived type 'mpi_datatype' at (1) is being used before it is defined
src/communications/exchange_particles.F90:80:22:

   80 |     type(MPI_REQUEST), allocatable :: mpi_req(:)
      |                      1
Error: Derived type 'mpi_request' at (1) is being used before it is defined
src/communications/exchange_particles.F90:81:21:

   81 |     type(MPI_STATUS) :: istat
      |                     1
Error: Derived type 'mpi_status' at (1) is being used before it is defined
src/communications/exchange_particles.F90:91:14:

   91 |     allocate (mpi_req(sendrecv_neighbors))
      |              1
Error: Allocate-object at (1) is neither a data pointer nor an allocatable variable
src/communications/exchange_particles.F90:658:22:

  658 |     type(MPI_REQUEST), allocatable :: mpi_req(:)
      |                      1
Error: Derived type 'mpi_request' at (1) is being used before it is defined
src/communications/exchange_particles.F90:659:21:

  659 |     type(MPI_STATUS) :: istat
      |                     1
Error: Derived type 'mpi_status' at (1) is being used before it is defined
src/communications/exchange_particles.F90:670:14:

  670 |     allocate (mpi_req(sendrecv_neighbors))
      |              1
Error: Allocate-object at (1) is neither a data pointer nor an allocatable variable

Let me know if this makes sense to you.

Thanks,
Ramandeep Gill

**Comment by haykh** [comment]
sorry for the delay. just saw your issue. that is weird. could you send the exact `configure` command you're using? also, can you show the output of `h5pfc --version`?

from your error it seems it's just not cross-compiling the MPI for some reason. you tried both `-mpi` and `-mpi08`, right? and you did include the `-hdf5`?

**Comment by rgill3141** [comment]
Thanks for writing back.

The `configure` command that I'm using is this: `python configure.py -mpi08 -hdf5 --user=user_2d_rec -2d`
My python version is: `Python 3.11.5`
h5pfc version: `GNU Fortran (conda-forge gcc 13.2.0-2) 13.2.0`

And yes, I tried both `-mpi` and `-mpi08`. The former gives similar types of errors for the same file.

**Comment by haykh** [comment]
what i was wondering is whether the conda-forge version of the hdf5 is built with openmpi, which is what you're using as an MPI backend, as opposed to mpich.

**Comment by rgill3141** [comment]
The conda-forge hdf5 compiler doesn't come with the parallel version `h5pfc`. That's why I had to compile it from source with the parallel option. However, I did use the conda-forge `gcc` and `opemmpi` compilers to build it.

**Comment by haykh** [comment]
could you send the full set of commands to reproduce this? i'm trying to recreate this with the same exact versions in a `docker` container, and failing miserably. 

also, we do have `docker` [support](https://github.com/PrincetonUniversity/tristan-mp-v2/tree/master/docker), so theoretically, if you're running this on your machine, you can use that (it'll install all the dependencies for yourself), or just use the same `apt` commands as in the [Dockerfile](https://github.com/PrincetonUniversity/tristan-mp-v2/blob/master/docker/Dockerfile) to install the modules properly.

**Comment by rgill3141** [comment]
I'm not sure what you mean by 'full set of commands'. If you can tell me what information you need to be able to recreate this problem, I can try to provide that to you.

I tried the docker route, but you need to have root privilege for installation. I was able to install docker-compose locally with conda, but I guess that's useless without docker. I can check with the system admins tomorrow to see if they can install it.

**Comment by rgill3141** [comment]
Is there a way to see that when I issue `make all` after configuring tristan, what compilers and libraries it is actually using? Maybe that might shed some light on whether the make command is picking up all the right stuff from the path. I just made sure that all my newly installed compilers and libraries are in fact on the path.

**Comment by rgill3141** [comment]
Okay, problem solved!

Initially, my libraries were not on the path and the linker was picking up older libraries and failing. Then, when I put them on the path, I didn't issue `make clean` and start over again. So, it was still getting stuck at the same step. After `make clean`, it all fell into place.

I should've checked this. I'm sorry to have wasted you time. Thanks for your help.
