### ISSUE TITLE
What are enrg1 and enrg2 keys in fields (for two particle species)?

### ISSUE THREAD

**Issue by rgill3141** [PrincetonUniversity/tristan-mp-v2#14]
The dict keys in fields show two keys: `enrg1` and `enrg2`. Are these the energy densities (or energies) of the two particle species? And what are the units? I couldn't find any mention of these in the online code guide.

**Comment by haykh** [comment]
Sorry, I just noticed this issue. `enrg*` are the energy densities of particular species.
