### ISSUE TITLE
tristanVis

### ISSUE THREAD

**Issue by Tissot11** [PrincetonUniversity/tristan-mp-v2#17]
Hi, I am also having the same problem again as in #9. After reading the discussion, I copied aux.py from c5c3172 commit. However, I had to make changes in the import  tristan.aux as aux line in tristanVis.py file. I also see couple of new functions added causing conflict with newer files in tristanVis folder. Is there is a basic version of python scripts that can be made available to read the data and do the visualization as documented on the documentation page?

**Comment by haykh** [comment]
duplicating here from #9: the package is in early access, but you can use it already, it has most of the features you might need: https://github.com/haykh/graph-et/

as opposed to traditional data read, it supports "lazy-loading," meaning it only reads the metadata first, and loads the actual data only when you need it (helps when your simulation is TBs). Let me know if you have question on how to use it, will be happy to assist.

**Comment by Tissot11** [comment]
Thanks! I'll try it today.
