### ISSUE TITLE
tristanVis.aux module missing

### ISSUE THREAD

**Issue by omguptaup** [PrincetonUniversity/tristan-mp-v2#9]
When I try to visualize using tristanVis package, I get the following error
-----
ModuleNotFoundError                       Traceback (most recent call last)
/home/username/Programs/tristan-mp-v2/vis_start.ipynb Cell 1 in <cell line: 1>()
----> [1](vscode-notebook-cell:/home/og5399/Programs/tristan-mp-v2/vis_start.ipynb#W0sZmlsZQ%3D%3D?line=0) import tristanVis.tristanVis as tVis
      [2](vscode-notebook-cell:/home/og5399/Programs/tristan-mp-v2/vis_start.ipynb#W0sZmlsZQ%3D%3D?line=1) import tristanVis.snippets as trS
      [3](vscode-notebook-cell:/home/og5399/Programs/tristan-mp-v2/vis_start.ipynb#W0sZmlsZQ%3D%3D?line=2) import tristanVis.isolde as isolde

File ~/Programs/tristan-mp-v2/tristanVis/tristanVis.py:1, in <module>
----> 1 import tristanVis.aux as aux
      3 from contextlib import contextmanager
      4 import ipywidgets as ipyW

ModuleNotFoundError: No module named 'tristanVis.aux'

Kindly help with this issue

**Comment by rgill3141** [comment]
Was this issue resolved?

**Comment by rgill3141** [comment]
The module `aux.py` can be found in an earlier commit: `c5c3172` of the code. I just copied that file into the tristanVis folder. That solved the problem!

I wonder why it is no longer included in the current version.

**Comment by omguptaup** [comment]
Ah. Thank you, Dr. Gill! I will try this out

**Comment by haykh** [comment]
@rgill3141 @omguptaup thanks for solving this. The main reason was that most of the users were actually using the `iseult.py`, so I discontinued the `tristanVis.py`, which might have not been the best idea. But I am currently working on a more solid solution which will do things much faster with parallel lazy loading, etc. I don't have a timeline yet, so stay tuned (this is not my main job at this point, but I try to continue the support as much as I can).

Also, if you modify something and want to add to the main repository -- please feel free to add a pull request.

**Comment by rgill3141** [comment]
I see. I didn't even know about the `iseult.py` module until you mentioned it. There's no mention of it on the Tristan V2 visualization page. It would really help if someone added this info on the webpage.

**Comment by haykh** [comment]
I do have it described right [here](https://princetonuniversity.github.io/tristan-v2/tristanv2-visualization.html#python-module). It's not for visualization per-se, just a collection of handy function to import the hdf5 data for particles, fields, spectra, etc.

**Comment by rgill3141** [comment]
I've been using all what appears on the visualization page for my problem and it is really useful.

**Comment by haykh** [comment]
Glad to hear! I'm working on a new code currently, but some of the libraries will migrate also to `Tristan v2`, will tag you once that's done in this thread. I'm closing this issue for now. Feel free to reopen if there are still issues.

**Comment by haykh** [comment]
@rgill3141 @omguptaup the data read & vis package is available (it's in pretty early stage, so some errors are possible). but i'm constantly using it for my own purposes, so should work. 
if you want, please feel free to use it: https://github.com/haykh/graph-et/
